// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package google_wire

import (
	"github.com/google/wire"
	"io"
	"os"
)

// Injectors from injector.go:

func InitializedService(isError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializedDatabaseRepository() *DatabaseRepository {
	dbPostgreSQL := NewDatabasePostgreSQL()
	dbMongoDB := NewDatabaseMongoDB()
	databaseRepository := NewDatabaseRepository(dbPostgreSQL, dbMongoDB)
	return databaseRepository
}

func InitializedFooBarService(foo Foo, bar Bar) *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository, foo)
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository, bar)
	fooBarService := NewFooBarService(fooService, barService)
	return fooBarService
}

func InitializedSayHelloService() *SayHelloService {
	sayHelloImpl := NewSayHelloImpl()
	sayHelloService := NewSayHelloService(sayHelloImpl)
	return sayHelloService
}

func InitializedFooBarServiceStruct(foo Foo, bar Bar) *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository, foo)
	fooBarService := &FooBarService{
		FooService: fooService,
	}
	return fooBarService
}

func InitializedFooBarStructUsingValue() *FoobarStruct {
	fooStruct := _wireFooStructValue
	barStruct := _wireBarStructValue
	foobarStruct := &FoobarStruct{
		FooStruct: fooStruct,
		BarStruct: barStruct,
	}
	return foobarStruct
}

var (
	_wireFooStructValue = fooValue
	_wireBarStructValue = barValue
)

func InitializedReader() io.Reader {
	reader := _wireFileValue
	return reader
}

var (
	_wireFileValue = os.Stdin
)

func InitializedConfiguration() *Configuration {
	application := NewApplication()
	configuration := application.Configuration
	return configuration
}

// injector.go:

var fooSet = wire.NewSet(NewFooRepository, NewFooService)

var barSet = wire.NewSet(NewBarRepository, NewBarService)

var sayHelloSet = wire.NewSet(
	NewSayHelloImpl, wire.Bind(new(SayHello), new(*SayHelloImpl)),
)

var fooValue = &FooStruct{}

var barValue = &BarStruct{}
