// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package google_wire

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializedService(isError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializedDatabaseRepository() *DatabaseRepository {
	dbPostgreSQL := NewDatabasePostgreSQL()
	dbMongoDB := NewDatabaseMongoDB()
	databaseRepository := NewDatabaseRepository(dbPostgreSQL, dbMongoDB)
	return databaseRepository
}

func InitializedFooBarService(foo Foo, bar Bar) *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository, foo)
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository, bar)
	fooBarService := NewFooBarService(fooService, barService)
	return fooBarService
}

// injector.go:

var fooSet = wire.NewSet(NewFooRepository, NewFooService)

var barSet = wire.NewSet(NewBarRepository, NewBarService)
