### Get All
GET localhost:8080/api/salaries
Accept: application/json
x-api-key: rahasia

### Create
POST localhost:8080/api/salaries
Content-Type: application/json
Accept: application/json
x-api-key: rahasia


{
  "role": "UI/UX",
  "company": "Shopee",
  "expr":5,
  "salary": 20000000
}

### Find By Id
GET localhost:8080/api/salaries/1
Accept: application/json
x-api-key: rahasia

### Update
PUT localhost:8080/api/salaries/3
Content-Type: application/json
Accept: application/json
x-api-key: rahasia

{
  "role": "Backend Developer",
  "company": "Gojek",
  "expr": 1,
  "salary": 8000000
}

### Delete
DELETE localhost:8080/api/salaries/4
Accept: application/json
x-api-key: rahasia
