// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator"
	"go-salaries-app/app"
	"go-salaries-app/controller"
	"go-salaries-app/middleware"
	"go-salaries-app/repository"
	"go-salaries-app/service"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	salaryRepository := repository.NewSalaryRepository()
	db := app.NewDB()
	validate := validator.New()
	salaryService := service.NewSalaryService(salaryRepository, db, validate)
	salaryController := controller.NewSalaryController(salaryService)
	router := app.NewRouter(salaryController)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}
